version: '3.4'

services:
  employee-tree:
    build: ../employee-tree
    environment:
      - "spring.profiles.active=docker"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 1m
    links:
      - eureka
    networks:
      - test_net

  eureka:
    image: "springcloud/eureka"
    ports:
      - "8761:8761"
    networks:
      - test_net

networks:
  test_net:
    driver: bridge
