spring:
  application:
    name: mentor-tree

feign:
  employee-client:
    name: employee-tree

---
spring:
  profiles: local

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

server:
  port: 8081

---
spring:
  profiles: integration

logging:
  level:
    ROOT: DEBUG

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
